#!/usr/bin/env bash

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh"  # Loads all defined icons

PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored

FONT="Inter" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
FONT_MONO="JetBrainsMono Nerd Font"
FONT_ICON="$FONT_MONO"
SPACE_CLICK_SCRIPT="yabai -m space --focus \$SID 2>/dev/null" # The script that is run for clicking on space components

PADDINGS=6 # All paddings use this value (icon, label, background and bar paddings)
PADDINGS_SMALL=3

POPUP_BORDER_WIDTH=3
POPUP_CORNER_RADIUS=11

SHADOW=off

# Setting up the general bar appearance and default values
sketchybar --bar \
  height=32 \
  corner_radius=0 \
  border_width=0 \
  border_color=0xff909090 \
  margin=0 \
  margin_bottom=0 \
  blur_radius=8 \
  position=top \
  padding_left=2 \
  padding_right=2 \
  color=$BAR_COLOR \
  topmost=off \
  font_smoothing=on \
  y_offset=0 \
  shadow=$SHADOW \
  notch_width=200 \
  --default \
  drawing=on \
  updates=when_shown \
  label.font="$FONT:Medium:12.0" \
  icon.font="$FONT_ICON:Regular:12.0" \
  icon.color=$ICON_COLOR \
  label.color=$LABEL_COLOR \
  icon.padding_left=$PADDINGS \
  icon.padding_right=$PADDINGS_SMALL \
  label.padding_left=$PADDINGS_SMALL \
  label.padding_right=$PADDINGS \
  background.padding_right=$PADDINGS \
  background.padding_left=$PADDINGS \
  background.corner_radius=9999 \
  popup.background.border_width=$POPUP_BORDER_WIDTH \
  popup.background.corner_radius=$POPUP_CORNER_RADIUS \
  popup.background.border_color=$POPUP_BORDER_COLOR \
  popup.background.color=$POPUP_BACKGROUND_COLOR \
  popup.background.shadow.drawing=$SHADOW

# APPLE_POPUP_OFF="sketchybar --set apple.logo popup.drawing=off"
# APPLE_POPUP_CLICK_SCRIPT="sketchybar --set \$NAME popup.drawing=toggle"

# sketchybar --add item           apple.logo left                             \
#                                                                             \
#            --set apple.logo     icon=$APPLE                                 \
#                                 icon.font="$FONT:Black:16.0"                \
#                                 icon.color=$GREEN                           \
#                                 label.drawing=off                           \
#                                 click_script="$APPLE_POPUP_CLICK_SCRIPT"    \
#                                 background.color=$BRACKET_BG \
#                                 background.height=$BRACKET_HEIGHT \
#                                 icon.padding_right=12 \
#                                 icon.padding_left=12
#                                                                             \
#            --add item           apple.prefs popup.apple.logo                \
#            --set apple.prefs    icon=$PREFERENCES                           \
#                                 label="Preferences"                         \
#                                 click_script="open -a 'System Preferences';
#                                               $APPLE_POPUP_OFF"             \
#                                                                             \
#            --add item           apple.activity popup.apple.logo             \
#            --set apple.activity icon=$ACTIVITY                              \
#                                 label="Activity"                            \
#                                 click_script="open -a 'Activity Monitor';
#                                               $APPLE_POPUP_OFF"             \
#                                                                             \
#            --add item           apple.lock popup.apple.logo                 \
#            --set apple.lock     icon=$LOCK                                  \
#                                 label="Lock Screen"                         \
#                                 click_script="pmset displaysleepnow;
#                                               $APPLE_POPUP_OFF"

###
### Left
###

# Register custom event - this will be use by sketchybar's space items as well as app_space.sh
sketchybar --add event window_change

# Space items
COLORS_SPACE=($COLOR_YELLOW $COLOR_CYAN $COLOR_MAGENTA $COLOR_WHITE $COLOR_BLUE $COLOR_RED $COLOR_GREEN)
LENGTH=${#ICONS_SPACE[@]}

for i in "${!ICONS_SPACE[@]}"; do
  sid=$((i + 1))
  PAD_LEFT=2
  PAD_RIGHT=2
  if [[ $i == 0 ]]; then
    PAD_LEFT=8
  elif [[ $i == $((LENGTH - 1)) ]]; then
    PAD_RIGHT=8
  fi
  sketchybar --add space space.$sid left \
    --set space.$sid script="$PLUGIN_DIR/app_space.sh" \
    associated_space=$sid \
    padding_left=$PAD_LEFT \
    padding_right=$PAD_RIGHT \
    background.color=${COLORS_SPACE[i]} \
    background.border_width=0 \
    background.corner_radius=6 \
    background.height=24 \
    icon=${ICONS_SPACE[i]} \
    icon.color=${COLORS_SPACE[i]} \
    label="_" \
    label.color=${COLORS_SPACE[i]} \
    click_script="$SPACE_CLICK_SCRIPT" \
    --subscribe space.$sid front_app_switched window_change
done

# Space bracket
sketchybar --add bracket spaces '/space\..*/' \
  --set spaces background.color=$COLOR_BACKGROUND

# "" ""

sketchybar --add item separator left \
  --set separator icon= \
  icon.font="$FONT_ICON:Semibold:14.0" \
  background.padding_left=8 \
  background.padding_right=0 \
  label.drawing=off \
  icon.color=$WHITE

sketchybar --add event window_focus \
  --add item system.yabai left \
  --set system.yabai script="$PLUGIN_DIR/yabai.sh" \
  icon.font="$FONT_ICON:Regular:16.0" \
  label.drawing=off \
  icon=$YABAI_GRID \
  icon.color=$GREEN \
  updates=on \
  --subscribe system.yabai window_focus mouse.clicked \
  --add item front_app left \
  --set front_app script="$PLUGIN_DIR/front_app.sh" \
  icon.drawing=off \
  background.padding_left=0 \
  label.color=$WHITE \
  label.font="$FONT:Semibold:13.0" \
  label.padding_left=0 \
  --subscribe front_app front_app_switched

###
### Right
###

sketchybar --add item time right \
  --set time update_freq=5 \
  icon= \
  script="$PLUGIN_DIR/time.sh" \
  label= \
  icon.padding_left=8 \
  background.color=$BRACKET_BG \
  background.height=$BRACKET_HEIGHT \
  background.padding_left=3 \
  background.padding_right=0

sketchybar --add item calendar right \
  --set calendar update_freq=30 \
  icon= \
  icon.padding_left=11 \
  icon.padding_right=4 \
  label.padding_right=11 \
  script="$PLUGIN_DIR/date.sh" \
  background.color=$BRACKET_BG \
  background.height=$BRACKET_HEIGHT \
  background.padding_left=3 \
  background.padding_right=3

sketchybar --add item battery right \
  --set battery update_freq=5 \
  script="$PLUGIN_DIR/power.sh" \
  background.color=$BRACKET_BG \
  background.height=$BRACKET_HEIGHT \
  label.padding_right=11 \
  icon.padding_left=10 \
  icon.padding_right=9 \
  background.padding_left=3 \
  background.padding_right=3 \
  icon=

sketchybar --add item volume right \
  --set volume script="$PLUGIN_DIR/volume.sh" \
  background.color=$BRACKET_BG \
  background.height=$BRACKET_HEIGHT \
  label.padding_right=10 \
  icon.padding_left=9 \
  icon.padding_right=6 \
  background.padding_left=3 \
  background.padding_right=3 \
  update_freq=5 \
  icon=

sketchybar --add item cpu.percent right \
  --set cpu.percent label= \
  icon= \
  update_freq=3 \
  background.color=$BRACKET_BG \
  background.height=$BRACKET_HEIGHT \
  label.padding_right=10 \
  icon.padding_left=10 \
  icon.padding_right=6 \
  background.padding_left=3 \
  background.padding_right=3 \
  script="$PLUGIN_DIR/cpu.sh"

sketchybar --add bracket primary_spaces \
  space.1 \
  space.2 \
  space.3 \
  space.4 \
  space.5 \
  space.6 \
  space.7 \
  space.8 \
  space.9 \
  space.10 \
  space.11 \
  --set primary_spaces \
  background.color=$BRACKET_BG \
  background.height=$BRACKET_HEIGHT \
  background.padding_left=8 \
  background.padding_right=8

sketchybar --add bracket secondary_spaces \
  space.12 \
  space.13 \
  space.14 \
  space.15 \
  --set secondary_spaces \
  background.color=$BRACKET_BG \
  background.height=$BRACKET_HEIGHT \
  background.padding_left=8 \
  background.padding_right=8

############## FINALIZING THE SETUP ##############
sketchybar --update

echo "sketchybar configuation loaded.."
