[general]
import = [
  "~/.config/alacritty/main.toml",
  "~/.config/alacritty/keybindings.toml",
  "~/.config/alacritty/themes/catppuccin-macchiato.toml",
  # "~/.config/alacritty/themes/catppuccin-mocha.toml",
  "~/.config/alacritty/custom.toml"
]
