{ pkgs, lib, inputs, modulesPath, ... }:
with lib;
with lib.my; {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    inputs.nixos-apple-silicon.nixosModules.default
  ];

  config = {
    # host options
    modules = {
      desktop.enable = true;
      dev.enable-all = true;
      wayland.enable = true;
      wayland.hyprland.enable = true;
      wayland.hyprland.extraConf = ''
        input {
            sensitivity = 0.0
            kb_options = ctrl:nocaps,altwin:swap_alt_win
        }
      '';
      programs.alacritty.enable = true;
      services.protonmail.enable = true;
      services.protonvpn.configFile =
        "/private/wg-quick/protonvpn-1-US-VA-14.conf";
    };
    host.optimize = false;
    # asahi system
    nixpkgs.hostPlatform = "aarch64-linux";
    hardware.asahi.peripheralFirmwareDirectory = ./firmware;
    hardware.asahi.useExperimentalGPUDriver = true;
    modules.linux.systemd-boot = false;
    boot.loader.systemd-boot.enable = true;
    boot.loader.efi.canTouchEfiVariables = false;
    services.pipewire.alsa.support32Bit = mkForce false;
    # kernel
    boot.initrd.availableKernelModules = [ "usb_storage" "sdhci_pci" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ ];
    boot.extraModulePackages = [ ];
    # hardware
    fileSystems = {
      "/" = {
        device = "/dev/disk/by-uuid/306067e8-7411-4be4-b50e-b88cf4fb8e4c";
        fsType = "ext4";
      };
      "/boot" = {
        device = "/dev/disk/by-uuid/4117-15EC";
        fsType = "vfat";
      };
    };
    swapDevices = [ ];
    # networking
    networking.wireless.iwd = {
      enable = true;
      settings.General.EnableNetworkConfiguration = true;
    };
    networking.useDHCP = lib.mkDefault true;
    networking.firewall.enable = false;

    environment.systemPackages = with pkgs; [ spotify-player ];

    ### autogenerated by installer, do not edit
    system.stateVersion = "24.05";
  };
}
