#!/usr/bin/env bash

name=$(basename "$0")

if [ "$name" == "change-brightness" ]; then
  execute=1
else
  execute=
fi

echoerr() { printf "%s\n" "$*" >&2; }

d_brightness="$3"

brightness=""
if [ -n "$d_brightness" ]; then
  brightness="$2 $3"
else
  brightness="$2"
fi

ddc_param=10

if [ "$execute" == "1" ]; then
  set -eu
else
  set -e
fi

bus=
model=
value_file=
popup_file=

function parse_bus() {
  bus="$1"
  if [ "$bus" == "5" ]; then
    model="PA32U"
  elif [ "$bus" == "6" ]; then
    model="DELL P2715Q"
  else
    echoerr "Unknown display (bus=${bus})"
  fi
  model_id=${bus// /_}
  value_file="$HOME/.brightness-value-${model_id}"
  popup_file="$HOME/.brightness-popup-${model_id}"
}

function cleanup_notify_files() {
  local x
  for x in "$popup_file" "$value_file"; do
    if [ -e "$x" ]; then
      if [ -z "$(cat "$x")" ]; then
        rm "$x"
      fi
    fi
  done
}

function update_notify() {
  set +u
  expire_time="$1"
  text="$2"
  value="$3"
  if [ "$execute" == "1" ]; then
    set -u
  fi
  args=("--expire-time=$expire_time"
    "--hint" "int:transient:1"
    "--hint" "string:image-path:video-display"
    "--replace-file=$popup_file")
  if [ -n "$value" ]; then
    args+=("--hint" "int:value:$value")
  fi
  args+=("$model: Brightness" "$text")
  cleanup_notify_files
  notify-send.sh "${args[@]}"
}

function current_brightness() {
  if [ -f "$value_file" ]; then
    cat "$value_file"
  else
    exit 1
  fi
}

function get_update_summary() {
  if [ -n "$current" ]; then
    echo -n "$current% / 100%"
  else
    echo -n "$brightness% / 100%"
  fi
}

function ddc_wait() {
  for x in {1..80}; do
    pids="$(pidof ddcutil || echo -n '')"
    if [ -n "$pids" ]; then
      sleep 0.025
    else
      return 0
    fi
  done
  return 1
}

function run_set() {
  ddc_wait
  sudo ddcutil --maxtries 6,6,6 --disable-udf --disable-usb --skip-ddc-checks --verify \
    --sleep-multiplier=0.066 --disable-dynamic-sleep -b "$bus" \
    setvcp $ddc_param $brightness
}

function run_display() {
  local BRIGHTNESS=""
  if [ -z "$d_brightness" ]; then
    BRIGHTNESS="$brightness"
    echo "$brightness" >"$value_file"
  else
    BRIGHTNESS=$(get-brightness "$bus")
  fi

  update_notify 1000 "$BRIGHTNESS% / 100%" "$BRIGHTNESS"
}

if [ "$execute" == "1" ]; then
  parse_bus "$1"
  current="$(current_brightness || get-brightness "$bus")"

  run_set ||
    (ddc_wait && sleep 0.05 && run_set) ||
    (update_notify 1000 "Write failed" && false)

  pre_notify=0
  if [ "$pre_notify" != "0" ]; then
    if [ -n "$d_brightness" ]; then
      update_notify 2500 "$(get_update_summary)" "$(current_brightness)"
    fi
  fi

  run_display || (update_notify 1000 "Read failed" && false)
fi
