{ config, lib, pkgs, inputs, modulesPath, ... }:
with lib;
let inherit (config) user;
in {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    inputs.nixos-apple-silicon.nixosModules.default
  ];

  config = {
    ## host options
    modules = {
      dev.enable-all = true;
      desktop.enable = true;
      # desktop.hyprland.flake = true;
      desktop.hyprland.extraConf = ''
        input {
            sensitivity = 0.0
            kb_options = ctrl:nocaps,altwin:swap_alt_win
        }
      '';
      programs.firefox.profilePath = "v5o56gix.default-1722656138151";
      services.protonmail.enable = true;
      services.protonvpn = {
        enable = false;
        configFile = "/private/wg-quick/protonvpn-1-US-VA-14.conf";
      };
      services.mpd = {
        enable = true;
        musicDirectory = "/mnt/huge/Music";
      };
    };
    ## asahi system
    boot.loader.systemd-boot.enable = true;
    boot.loader.efi.canTouchEfiVariables = false;
    nixpkgs.hostPlatform = "aarch64-linux";
    hardware.asahi.peripheralFirmwareDirectory = ./firmware;
    services.pipewire.alsa.support32Bit = mkForce false;
    ## kernel
    boot.initrd.availableKernelModules = [ "usb_storage" "sdhci_pci" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ ];
    boot.extraModulePackages = [ ];
    boot.kernelParams = [ ];
    ## hardware
    fileSystems = {
      "/" = {
        device = "/dev/disk/by-uuid/306067e8-7411-4be4-b50e-b88cf4fb8e4c";
        fsType = "ext4";
      };
      "/boot" = {
        device = "/dev/disk/by-uuid/4117-15EC";
        fsType = "vfat";
      };
    };
    ## networking
    networking.wireless.iwd.enable = true;
    networking.wireless.iwd.settings.General.EnableNetworkConfiguration = true;
    networking.useDHCP = true;
    ### autogenerated by installer, do not edit
    system.stateVersion = "24.05";
  };
}
