#!/usr/bin/env python3

import urllib
from urllib.request import urlopen
import json
import time
from os.path import expanduser

try:
    r = urlopen("https://api.ipify.org?format=json")
except urllib.error.HTTPError as e:
    print("http error: " + str(e))

j = json.loads(r.read().decode(encoding="UTF-8"))
print(j["ip"])
